### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by XionioXMaster** [infernalexp/Infernal-Expansion#304] opened 2021-10-18 12:18 UTC
**Describe the Bug:**
https://github.com/Loli-Server/LoliServer1.16/issues/230

**Version Information:**
 - Operating System: Unbuntu 20
 - Mod Version: 2.3.2
 - Minecraft Version: 1.16.5
 - Forge Version: 36.2.0
 - Other mods that were running when the crash happened: Nope

**Additional Context:**

**Comment by SwanX1** [comment] 2021-10-18 12:21
Duplicate of #303
We don't support modified software other than forge.
See: #158 #169 #264 #292

**Closed by SwanX1** 2021-10-18 12:21 UTC
Labels: bug
